

name = "iys"
compatibility_date = "2026-01-01"
main = "worker.js"

[assets]
directory = "./"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = iys-db"
database_id = "183d0310-04cb-42c8-9040-c031cf68297a"

[vars]
AMS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbxyCPzu-OHaY3_RdqUWKCyb53PDb4bpJb8O8hjMuCCaQheriNK811NXJ09BPz6sf8Vx/exec"
